#!/bin/bash
OCAML_VERSION=4.08.0
if ! command -v opam &> /dev/null
then
	echo "OPAM could not be found. Installing OPAM..."
	yes "\n" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
	yes | opam init --auto-setup --disable-sandboxing --yes --compiler=$OCAML_VERSION && opam clean
fi
apt install libz3-dev
opam switch create $OCAML_VERSION
eval `opam config env`
opam install --yes containers containers-data z3.4.8.1 core.v0.13.0 batteries.3.0.0 ocamlgraph.1.8.8 
if [ "$(uname)" == "Darwin" ]; then
	export DYLD_LIBRARY_PATH=~/.opam/${OCAML_VERSION}/lib/z3:$DYLD_LIBRARY_PATH
else
	export LD_LIBRARY_PATH=~/.opam/${OCAML_VERSION}/lib/z3:$LD_LIBRARY_PATH
fi

